../src/global_pkg.sv
../src/uart_pkg.sv
../src/fifo_pkg.sv
../src/processor_pkg.sv
../src/and_start.sv
../src/clkdiv.sv
../src/cmd_fsm.sv
../src/counter.sv
../src/fifo_matrix.sv
../src/fifo_vector.sv
../src/fsm_fifo.sv
../src/fsm_processor.sv
../src/interrupt_rgstr.sv
../src/logic_and.sv
../src/logic_xor.sv
../src/nibb_reg.sv
../src/piso_lsb.sv
../src/pointers.sv
../src/pointers_M.sv
../src/processor.sv
../src/processors_if.sv
../src/ram_matrix.sv
../src/ram_vector.sv
../src/register.sv
../src/rx_fsm.sv
../src/rx_top.sv
../src/sipo.sv
../src/time_mux.sv
../src/top_cmd.sv
../src/top_processors.sv
../src/tx_fsm.sv
../src/tx_mux.sv
../src/tx_top.sv
../src/uart.sv
../src/top_p03.sv
../src/top_p03_tb.sv
top_tb_p03.sv