../src/Global_Pkg.sv
../src/top_mdr.sv
../src/adder.sv
../src/comb_qshift1.sv
../src/comb_qshift2.sv
../src/control_operation.sv
../src/counter.sv
../src/debounce.sv
../src/demux.sv
../src/left_shift.sv
../src/mix_regs.sv
../src/mux2_1.sv
../src/mux3_1.sv
../src/mux4_2.sv
../src/or_m.sv
../src/q_exit.sv
../src/register.sv
../src/rightvshift.sv
../src/statemachine.sv
../src/subtractor.sv
tb_p02.sv