../src/uart_pkg.sv
../src/clkdiv.sv
../src/counter.sv
../src/debounce.sv
../src/time_mux.sv
../src/top.sv
../src/sipo.sv
../src/rx_fsm.sv
../src/logic_and.sv
../src/logic_xor.sv
../src/register.sv
../src/tx_fsm.sv
../src/piso_lsb.sv
../src/tx_mux.sv
../src/tx_top.sv
../src/rx_top.sv
tb_p03.sv